- type: playTimeTracker
  id: JobFreelancer

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobInventorySpecialist
