- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  setPreference: true #floof - this toggle allows players to ready up / create loadouts as senior roles. false disables it from the job
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 40.0h # Floofstation 40 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    #id: AtmosPDA # DeltaV: different PDAs in loadouts
    #belt: ClothingBeltUtilityEngineering # Floofstation - disabled this since they can choose between belts in loadout
    ears: ClothingHeadsetEngineering

- type: chameleonOutfit
  id: SeniorEngineerChameleonOutfit
  job: SeniorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
